In [11]:
import numpy as np

l=[1,2,3]
a=np.array([1,2,3])
print(type(l))
print(type(a))
print(l)
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3]
[1 2 3]


In [12]:
l.append(4)
print(l)

a.append(4)
print(a)

[1, 2, 3, 4]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [13]:
for e in a:
    print (e)

1
2
3


In [14]:
for e in l:
    print (e)

1
2
3
4


In [15]:
l=l+[5]
l

[1, 2, 3, 4, 5]

In [16]:
a=a+[4,5]
print(a)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [17]:
#the plus sign with list does concatanation whlie with nparray does vector addition

a=a+a                           #2*a is same as a+a
print(a)

[2 4 6]


# for numpy array most of the function act element wise while 

In [18]:
l=l+l                            #2*l is same as l+l
print(l)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [19]:
#list addition
l2=[]
for e in l:
    l2.append(e+e)
    
print(l2)

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]


In [20]:
np.sqrt(a)

array([1.41421356, 2.        , 2.44948974])

In [21]:
np.log(a)

array([0.69314718, 1.38629436, 1.79175947])

In [22]:
np.exp(a)

array([  7.3890561 ,  54.59815003, 403.42879349])

# for list if you want to do operation then you have to use the for loop


In [23]:
l3=[]
for e in l:
    l3.append(e*e)
    
print(l3)

[1, 4, 9, 16, 25, 1, 4, 9, 16, 25]


## for dot product


In [24]:
c=np.array([1,2])
d=np.array([2,1])
np.dot(c,d)

4

In [25]:
np.sum(c*d)

4

In [26]:
(c*d).sum()

4

In [27]:
c.dot(d)

4

In [28]:
cmag=np.sqrt((c*c).sum())
dmag=np.sqrt((d*d).sum())
cosangle=c.dot(d)/(cmag*dmag)
print(cosangle)

0.7999999999999998


In [29]:
angle=np.arccos(cosangle)
print(angle)

0.6435011087932847


# to convert matrix into array

In [30]:
m=np.matrix([[1,2],[3,4]])
m

matrix([[1, 2],
        [3, 4]])

In [31]:
a2=np.array(m)
a2

array([[1, 2],
       [3, 4]])

# to find the transpose

In [32]:
a2.T

array([[1, 3],
       [2, 4]])

# matrix operation

In [33]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
O=np.ones((10,10))
print(O)
O.mean()

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


1.0

In [35]:
r=np.random.random(10)
print(r)

[0.06094332 0.06998677 0.49348037 0.93773376 0.53052351 0.71010694
 0.78590129 0.98381558 0.8105606  0.70259888]


In [36]:
r.mean()

0.6085651009773432

In [37]:
ainv=np.linalg.inv(a2)
ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [38]:
ainv.dot(a2)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [39]:
np.linalg.det(a2)

-2.0000000000000004

In [40]:
np.diag(a2)

array([1, 4])

# solving linear equation

In [42]:
a=np.array([[1,1],[1.5,4]])         #x+y=2200 and 1.5x+4y=5050
b=np.array([2200,5050])
np.linalg.solve(a,b)

array([1500.,  700.])

# data loading using for loop

In [43]:
X=[]
import numpy as np
for line in open("file_name"):
    row=line.split(',')
    sample=map(float,row)
    X.append(sample)
    
print(X)

FileNotFoundError: [Errno 2] No such file or directory: 'file_name'