In [1]:
import numpy as np
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a.max())
print(a.min())
print(a)

9
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
b=np.linspace(1,3,5)
print(b)

[1.  1.5 2.  2.5 3. ]


In [4]:
a=a.reshape(3,3)  #reshape
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(a[0:3,0:2]) #slicing

[[1 2]
 [4 5]
 [7 8]]


In [6]:
print(a.sum())

45


In [7]:
print(a[0:3,0:2].sum()) #print respected row

27


In [8]:
print(a.ndim)
print(a.itemsize)
print(a.dtype)

2
4
int32


In [9]:
print(a.sum(axis=1))  #axis=1 rows    axis=0 column

[ 6 15 24]


In [10]:
print(a.max(axis=0))

[7 8 9]


In [11]:
print(np.sqrt(a))  #square root

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [12]:
b=np.sqrt(a)

In [13]:
print(b.sum())

19.306000526035724


In [14]:
b=np.array([(1,2,3),(4,5,6),(7,8,9)]) #standard deviation
print(np.std(b))

2.581988897471611


In [15]:
print(np.vstack((a,b)))      #vertical concat

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(np.hstack((a,b)))          #horizontal concat

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [17]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
print(b.ravel())

[1 2 3 4 5 6 7 8 9]


In [19]:
import matplotlib.pyplot as plt
x=np.arange(0,3*np.pi,0.1)
y=np.cos(x)
plt.plot(x,y)
plt.show()

<Figure size 640x480 with 1 Axes>